Smashing Magazine Heatmap
anewman15/smashing-magazine-heatmap pull request #1
Opened 2020-04-15 15:55 UTC by anewman15

2020-04-17 11:59 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-04-17 12:14 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @anewman15 & @ElijahTobs  :wave:
-
You have done a splendid job! :tada: The project looks great. Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - FIX -The README.
The project's README's live link should be updated. The description is well documented, and also in the social links of @anewman15, let's replace the placeholders with the actual social links.
Please makes changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-04-17 12:29 UTC, anewman15 commented
Thanks @christianotieno, we have made the changes

2020-04-17 13:26 UTC, uryelah commented
Hello **Abdullah Numan & Elijah Ayandokun**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all good job fixing the readme file, how you present your projects will be very important for recruiters ;-) 🌟**

There are still a couple of requirements you'll need to implement in order to go to the next project. So keep calm and write markup 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] The navbar should position elements as they are in the original page. You could use divs to represent each nav icon, and remember to also add the text.

- [ ] Each article in the page should actually use the `<article>` tag, let's remember semantic html. So for the elements with the `.article` and similar classes make then articles, not divs.

- [ ] Remember to add the text and divs representing the images for each article. Text represents a lot of visual weight after all. 

-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-20 10:46 UTC, anewman15 commented
Thanks @uryelah. We have made the suggested changes

2020-04-20 11:44 UTC, uryelah requested changes
Good job improving the project since the last review, you still need to change some of the divs to articles. An article in HTMl is a block of content that makes sense on its own, [you can read more here if you want a refresher.](https://www.w3schools.com/html/html5_semantic_elements.asp)

---------     

## Required Changes 🏗 👷‍♀

2020-04-20 11:44 UTC, uryelah commented on index.html
> +      <div class="article1"></div>
- [ ] These, .article1, 2, 3, etc. Should be `<articles>`
- [ ] Remember to also add text to them.

2020-04-20 11:44 UTC, uryelah commented on index.html
> +    <div class="design-handbook">
This div and other ones are still missing some visual content. You don't need to literally copy the illustration and make it grey. You can just put the missing text and divs to represent any illustration or picture.

2020-04-20 14:00 UTC, anewman15 commented
Done @uryelah. I hope this is enough...

2020-04-20 17:32 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-04-20 17:42 UTC, addod19 approved these changes
## Status: Approved 🏆 🎈 

Hi **TEAM**, you did a great job fixing all the recommended changes pointed out by the previous TSE's 👍 congratulations. The project looks great and I hereby approve it 😃 
However, before we merge to master, let us apply the DRY rule to our CSS file. 🙂  Below is a image indicating part of the repeating code. Kindly look through them and make the fixes
![DP](https://user-images.githubusercontent.com/46388113/79782141-20306c00-832e-11ea-84fb-4aa5b5787b42.PNG)
Kindly update the README file with the right live link and add email to the author section

Good luck with your next projects 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

2020-04-20 19:50 UTC, ElijahTobs commented
@addod19 The DRY rule has been applied to our CSS file

2020-04-20 19:50 UTC, merged